TrainingArguments:
  num_epochs: 25
  warmup_steps: 500
  per_device_train_batch_size: 10
  weight_decay: 0.01
  logging_steps: 15
  evaluation_strategy: steps
  evaluation_steps: 500
  save_steps: 1e8
  accumulation_steps: 64